version: 2.1

jobs:
  test:
    parameters:
      docker-image:
        type: string
      clj-version:
        type: string
        default: 1.11.1
      jvm-opts:
        type: string
        default: -Xms512m -Xmx1024m -Djdk.attach.allowAttachSelf -Dclj-async-profiler.debug
      is-alpine:
        type: boolean
        default: false
    working_directory: ~/project
    docker:
      - image: << parameters.docker-image >>
    steps:
      - checkout
      - restore_cache:
          key: project-{{ checksum "build.boot" }}
      - when:
          condition: << parameters.is-alpine >>
          steps:
            - run: apk add --no-cache libstdc++
      - run: boot test
      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: project-{{ checksum "build.boot" }}
    environment:
      BOOT_CLOJURE_VERSION: << parameters.clj-version >>
      BOOT_JVM_OPTIONS: << parameters.jvm-opts >>
      BOOT_WATCHERS_DISABLE: "yes"
      DEBUG: "yes"

workflows:
  test_all_jdks:
    jobs:
      - test:
          matrix:
            parameters:
              docker-image:
                - clojure:openjdk-8-boot-bullseye
                - clojure:openjdk-11-boot-bullseye
              clj-version: ["1.9.0", "1.10.3", "1.11.1"]
      - test:
          matrix:
            parameters:
              docker-image:
                - clojure:temurin-17-boot-focal
                - clojure:temurin-18-boot-focal
              clj-version: ["1.10.3", "1.11.1"]
          # add-opens needed for Virgil to work
          jvm-opts: >-
            -Xms512m -Xmx1024m -Djdk.attach.allowAttachSelf -Dclj-async-profiler.debug
            --add-opens jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED
